export type TileCategory =
  | 'start'
  | 'market'
  | 'viewpoint'
  | 'beach'
  | 'road'
  | 'education'
  | 'politics'
  | 'wildlife'
  | 'island'
  | 'mall'
  | 'port'
  | 'industrial'
  | 'landmark'
  | 'influence'
  | 'jail'
  | 'nightlife'
  | 'show'
  | 'themepark'
  | 'placeholder'

export type BoardTile = {
  id: number
  name: string
  nameTh: string
  zone: string
  zoneTh: string
  category: TileCategory
  description: string
  descriptionTh: string
  landPrice?: number
}

export const boardTiles: BoardTile[] = [
  {
    id: 0,
    name: 'Investment Bank',
    nameTh: 'ธนาคารเพื่อการลงทุน',
    zone: 'Bangsaen + Nong Mon',
    zoneTh: 'บางแสน + หนองมน',
    category: 'start',
    description: 'Starting corner and investment hub for every player.',
    descriptionTh: 'จุดเริ่มต้นและศูนย์กลางการลงทุนสำหรับผู้เล่นทุกคน',
  },
  {
    id: 1,
    name: 'Bangsaen Fish Market',
    nameTh: 'ตลาดปลาบางแสน',
    zone: 'Bangsaen + Nong Mon',
    zoneTh: 'บางแสน + หนองมน',
    category: 'market',
    description: 'Japanese-style seafood market with strong food business potential.',
    descriptionTh: 'ตลาดอาหารทะเลสไตล์ญี่ปุ่นที่มีศักยภาพสูงสำหรับธุรกิจอาหาร',
    landPrice: 850000,
  },
  {
    id: 2,
    name: 'Khao Sam Muk Viewpoint',
    nameTh: 'จุดชมวิวเขาสามมุข',
    zone: 'Bangsaen + Nong Mon',
    zoneTh: 'บางแสน + หนองมน',
    category: 'viewpoint',
    description: 'Hilltop viewpoint with local monkeys, cafes, and Bangsaen sea views.',
    descriptionTh: 'จุดชมวิวบนยอดเขาที่มีลิงประจำถิ่น คาเฟ่ และวิวทะเลบางแสน',
    landPrice: 800000,
  },
  {
    id: 3,
    name: 'Wonnapha Beach',
    nameTh: 'หาดวอนนภา',
    zone: 'Bangsaen + Nong Mon',
    zoneTh: 'บางแสน + หนองมน',
    category: 'beach',
    description: 'Evening street food and beach hangout area popular with younger crowds.',
    descriptionTh: 'แหล่งสตรีทฟู้ดยามเย็นและจุดแฮงก์เอาต์ริมหาดที่เป็นที่นิยมของวัยรุ่น',
    landPrice: 900000,
  },
  {
    id: 4,
    name: 'Chonlamakwithi Bridge',
    nameTh: 'สะพานชลมารควิถี',
    zone: 'Bangsaen + Nong Mon',
    zoneTh: 'บางแสน + หนองมน',
    category: 'road',
    description: 'Scenic seaside road and bridge route for coastal traffic and tourism.',
    descriptionTh: 'สะพานและถนนเลียบชายทะเลที่สวยงามสำหรับสัญจรและท่องเที่ยวชายฝั่ง',
    landPrice: 750000,
  },
  {
    id: 5,
    name: 'Political Event',
    nameTh: 'เหตุการณ์ทางการเมือง',
    zone: 'Bangsaen + Nong Mon',
    zoneTh: 'บางแสน + หนองมน',
    category: 'politics',
    description: 'Board-wide political or public event that can affect every player.',
    descriptionTh: 'เหตุการณ์สาธารณะหรือการเมืองระดับจังหวัดที่ส่งผลต่อผู้เล่นทุกคน',
  },
  {
    id: 6,
    name: 'Nong Mon Market 1',
    nameTh: 'ตลาดหนองมน 1',
    zone: 'Bangsaen + Nong Mon',
    zoneTh: 'บางแสน + หนองมน',
    category: 'market',
    description: 'Local souvenir and food market area, first section.',
    descriptionTh: 'แหล่งรวมของฝากและร้านอาหารท้องถิ่น โซนที่หนึ่ง',
    landPrice: 850000,
  },
  {
    id: 7,
    name: 'Nong Mon Market 2',
    nameTh: 'ตลาดหนองมน 2',
    zone: 'Bangsaen + Nong Mon',
    zoneTh: 'บางแสน + หนองมน',
    category: 'market',
    description: 'Local souvenir and food market area, second section.',
    descriptionTh: 'แหล่งรวมของฝากและร้านอาหารท้องถิ่น โซนที่สอง',
    landPrice: 850000,
  },
  {
    id: 8,
    name: 'Bangsaen Beach 1',
    nameTh: 'ชายหาดบางแสน 1',
    zone: 'Bangsaen + Nong Mon',
    zoneTh: 'บางแสน + หนองมน',
    category: 'beach',
    description: 'Main beachfront land, first section.',
    descriptionTh: 'ที่ดินริมชายหาดหลัก โซนที่หนึ่ง',
    landPrice: 1000000,
  },
  {
    id: 9,
    name: 'Bangsaen Beach 2',
    nameTh: 'ชายหาดบางแสน 2',
    zone: 'Bangsaen + Nong Mon',
    zoneTh: 'บางแสน + หนองมน',
    category: 'beach',
    description: 'Main beachfront land, premium section of this zone.',
    descriptionTh: 'ที่ดินริมชายหาดหลัก โซนพรีเมียมของโซนนี้',
    landPrice: 1100000,
  },
  {
    id: 10,
    name: 'Burapha University',
    nameTh: 'มหาวิทยาลัยบูรพา',
    zone: 'Bangsaen + Nong Mon',
    zoneTh: 'บางแสน + หนองมน',
    category: 'education',
    description: 'Major university corner tile and student economy anchor.',
    descriptionTh: 'มหาวิทยาลัยหลักและจุดขับเคลื่อนเศรษฐกิจของกลุ่มนิสิต',
  },
  {
    id: 11,
    name: 'Bang Phra Reservoir',
    nameTh: 'อ่างเก็บน้ำบางพระ',
    zone: 'Sriracha + Laem Chabang',
    zoneTh: 'ศรีราชา + แหลมฉบัง',
    category: 'viewpoint',
    description: 'Large reservoir area for nature, exercise, and weekend traffic.',
    descriptionTh: 'อ่างเก็บน้ำขนาดใหญ่สำหรับพักผ่อนธรรมชาติ ออกกำลังกาย และการท่องเที่ยวช่วงวันหยุด',
    landPrice: 1100000,
  },
  {
    id: 12,
    name: 'Sriracha Tiger Zoo',
    nameTh: 'สวนเสือศรีราชา',
    zone: 'Sriracha + Laem Chabang',
    zoneTh: 'ศรีราชา + แหลมฉบัง',
    category: 'wildlife',
    description: 'Former Sriracha landmark area with strong family tourism value.',
    descriptionTh: 'อดีตแลนด์มาร์กสำคัญของศรีราชาที่มีคุณค่าด้านการท่องเที่ยวสำหรับครอบครัว',
    landPrice: 1200000,
  },
  {
    id: 13,
    name: 'Koh Loi Health Park',
    nameTh: 'สวนสุขภาพเกาะลอย',
    zone: 'Sriracha + Laem Chabang',
    zoneTh: 'ศรีราชา + แหลมฉบัง',
    category: 'viewpoint',
    description: 'Seaside health park and local leisure area near Koh Loi.',
    descriptionTh: 'สวนสุขภาพริมทะเลและแหล่งพักผ่อนหย่อนใจยอดนิยมใกล้เกาะลอย',
    landPrice: 1150000,
  },
  {
    id: 14,
    name: 'J-Park Nihon Mura',
    nameTh: 'เจพาร์ค นิฮอน มูระ',
    zone: 'Sriracha + Laem Chabang',
    zoneTh: 'ศรีราชา + แหลมฉบัง',
    category: 'market',
    description: 'Japanese-style community mall and lifestyle spot in Sriracha.',
    descriptionTh: 'คอมมูนิตี้มอลล์สไตล์ญี่ปุ่นและจุดนัดพบไลฟ์สไตล์ในศรีราชา',
    landPrice: 1400000,
  },
  {
    id: 15,
    name: 'Central Sriracha',
    nameTh: 'เซ็นทรัล ศรีราชา',
    zone: 'Sriracha + Laem Chabang',
    zoneTh: 'ศรีราชา + แหลมฉบัง',
    category: 'mall',
    description: 'Major shopping mall and commercial anchor for Sriracha.',
    descriptionTh: 'ศูนย์การค้าขนาดใหญ่และแกนกลางพาณิชย์ของศรีราชา',
    landPrice: 1800000,
  },
  {
    id: 16,
    name: 'Koh Sichang',
    nameTh: 'เกาะสีชัง',
    zone: 'Sriracha + Laem Chabang',
    zoneTh: 'ศรีราชา + แหลมฉบัง',
    category: 'island',
    description: 'Island destination connected to Sriracha tourism and ferry traffic.',
    descriptionTh: 'แหล่งท่องเที่ยวเกาะยอดนิยมที่เชื่อมต่อกับการท่องเที่ยวและท่าเรือศรีราชา',
    landPrice: 1350000,
  },
  {
    id: 17,
    name: 'Khao Kheow Open Zoo',
    nameTh: 'สวนสัตว์เปิดเขาเขียว',
    zone: 'Sriracha + Laem Chabang',
    zoneTh: 'ศรีราชา + แหลมฉบัง',
    category: 'wildlife',
    description: 'Super landmark wildlife attraction with high tourism draw.',
    descriptionTh: 'สวนสัตว์เปิดและแลนด์มาร์กระดับประเทศ ดึงดูดนักท่องเที่ยวสูงมาก',
    landPrice: 1700000,
  },
  {
    id: 18,
    name: 'Laem Chabang Industrial Estate 1',
    nameTh: 'นิคมอุตสาหกรรมแหลมฉบัง 1',
    zone: 'Sriracha + Laem Chabang',
    zoneTh: 'ศรีราชา + แหลมฉบัง',
    category: 'industrial',
    description: 'Industrial estate area tied to factories, jobs, and regional logistics.',
    descriptionTh: 'นิคมอุตสาหกรรมขนาดใหญ่ที่เชื่อมโยงกับโรงงาน งาน และโลจิสติกส์ภูมิภาค โซนแรก',
    landPrice: 1600000,
  },
  {
    id: 19,
    name: 'Laem Chabang Industrial Estate 2',
    nameTh: 'นิคมอุตสาหกรรมแหลมฉบัง 2',
    zone: 'Sriracha + Laem Chabang',
    zoneTh: 'ศรีราชา + แหลมฉบัง',
    category: 'industrial',
    description: 'Second industrial estate section with stronger production value.',
    descriptionTh: 'นิคมอุตสาหกรรมแหลมฉบังส่วนที่สอง มีมูลค่าการผลิตและขนส่งสูงกว่า',
    landPrice: 1800000,
  },
  {
    id: 20,
    name: 'Chonburi Prison',
    nameTh: 'เรือนจำชลบุรี',
    zone: 'Sriracha + Laem Chabang',
    zoneTh: 'ศรีราชา + แหลมฉบัง',
    category: 'jail',
    description: 'Corner tile for the Chonburi correctional facility, used as the jail space.',
    descriptionTh: 'เรือนจำชลบุรี ใช้เป็นช่องขังและพื้นที่พิเศษสำหรับคดี',
  },
  {
    id: 21,
    name: 'Amata Castle',
    nameTh: 'ปราสาทอมตะ',
    zone: 'Amata City + Phan Thong',
    zoneTh: 'อมตะซิตี้ + พานทอง',
    category: 'landmark',
    description: 'Iconic landmark for the Amata industrial area.',
    descriptionTh: 'แลนด์มาร์กที่เป็นสัญลักษณ์อันโดดเด่นของนิคมอุตสาหกรรมอมตะ',
    landPrice: 1500000,
  },
  {
    id: 22,
    name: 'Ninja Amata Market',
    nameTh: 'ตลาดนินจาอมตะ',
    zone: 'Amata City + Phan Thong',
    zoneTh: 'อมตะซิตี้ + พานทอง',
    category: 'market',
    description: 'Large worker and local market tied to the industrial economy.',
    descriptionTh: 'ตลาดนัดคนทำงานขนาดใหญ่ที่ผูกกับเศรษฐกิจอุตสาหกรรมในพื้นที่',
    landPrice: 1600000,
  },
  {
    id: 23,
    name: 'Pinthong Industrial Area 1',
    nameTh: 'นิคมอุตสาหกรรมปิ่นทอง 1',
    zone: 'Amata City + Phan Thong',
    zoneTh: 'อมตะซิตี้ + พานทอง',
    category: 'industrial',
    description: 'Industrial zone near the Chonburi manufacturing corridor, first section.',
    descriptionTh: 'เขตอุตสาหกรรมในระเบียงการผลิตชลบุรี โซนแรก',
    landPrice: 1800000,
  },
  {
    id: 24,
    name: 'Pinthong Industrial Area 2',
    nameTh: 'นิคมอุตสาหกรรมปิ่นทอง 2',
    zone: 'Amata City + Phan Thong',
    zoneTh: 'อมตะซิตี้ + พานทอง',
    category: 'industrial',
    description: 'Industrial zone near the Chonburi manufacturing corridor, second section.',
    descriptionTh: 'เขตอุตสาหกรรมในระเบียงการผลิตชลบุรี โซนที่สอง',
    landPrice: 1900000,
  },
  {
    id: 25,
    name: 'Global Tech Factory Zone 1',
    nameTh: 'เขตโรงงานเทคโนโลยีระดับโลก 1',
    zone: 'Amata City + Phan Thong',
    zoneTh: 'อมตะซิตี้ + พานทอง',
    category: 'industrial',
    description: 'Multinational technology factory area with high production value.',
    descriptionTh: 'แหล่งโรงงานเทคโนโลยีข้ามชาติที่มีมูลค่าการผลิตและการลงทุนสูง',
    landPrice: 2200000,
  },
  {
    id: 26,
    name: 'Global Tech Factory Zone 2',
    nameTh: 'เขตโรงงานเทคโนโลยีระดับโลก 2',
    zone: 'Amata City + Phan Thong',
    zoneTh: 'อมตะซิตี้ + พานทอง',
    category: 'industrial',
    description: 'Second multinational technology factory area with strong rental potential.',
    descriptionTh: 'แหล่งโรงงานเทคโนโลยีข้ามชาติส่วนที่สอง มีศักยภาพค่าเช่าที่แข็งแกร่ง',
    landPrice: 2300000,
  },
  {
    id: 27,
    name: 'Amata City Chonburi 1',
    nameTh: 'อมตะซิตี้ ชลบุรี 1',
    zone: 'Amata City + Phan Thong',
    zoneTh: 'อมตะซิตี้ + พานทอง',
    category: 'industrial',
    description: 'Major industrial estate land, first section.',
    descriptionTh: 'ที่ดินนิคมอุตสาหกรรมหลักเฟสแรก',
    landPrice: 2400000,
  },
  {
    id: 28,
    name: 'Amata City Chonburi 2',
    nameTh: 'อมตะซิตี้ ชลบุรี 2',
    zone: 'Amata City + Phan Thong',
    zoneTh: 'อมตะซิตี้ + พานทอง',
    category: 'industrial',
    description: 'Major industrial estate land, second section.',
    descriptionTh: 'ที่ดินนิคมอุตสาหกรรมหลักเฟสสอง',
    landPrice: 2500000,
  },
  {
    id: 29,
    name: 'Amata City Chonburi 3',
    nameTh: 'อมตะซิตี้ ชลบุรี 3',
    zone: 'Amata City + Phan Thong',
    zoneTh: 'อมตะซิตี้ + พานทอง',
    category: 'industrial',
    description: 'Premium industrial estate land and strongest section of this zone.',
    descriptionTh: 'ที่ดินนิคมอุตสาหกรรมเกรดพรีเมียมและทำเลดีที่สุดในโซนนี้',
    landPrice: 2800000,
  },
  {
    id: 30,
    name: 'Local Power Broker',
    nameTh: 'ผู้มีอิทธิพลท้องถิ่น',
    zone: 'Amata City + Phan Thong',
    zoneTh: 'อมตะซิตี้ + พานทอง',
    category: 'influence',
    description: 'Corner tile for influential local forces that can disrupt business plans.',
    descriptionTh: 'ช่องพิเศษของผู้มีอิทธิพลในพื้นที่ สามารถแทรกแซงหรือช่วยเหลือธุรกิจได้',
  },
  {
    id: 31,
    name: 'Lan Pho Naklua Market',
    nameTh: 'ตลาดลานโพธิ์นาเกลือ',
    zone: 'Pattaya',
    zoneTh: 'พัทยา',
    category: 'market',
    description: 'Seafood market area in Naklua with strong local trading potential.',
    descriptionTh: 'ตลาดอาหารทะเลสดในนาเกลือที่มีการค้าคึกคักและยอดนิยมของนักท่องเที่ยว',
    landPrice: 2000000,
  },
  {
    id: 32,
    name: 'Pattaya Floating Market',
    nameTh: 'ตลาดน้ำสี่ภาคพัทยา',
    zone: 'Pattaya',
    zoneTh: 'พัทยา',
    category: 'market',
    description: 'Tourist market and cultural shopping destination.',
    descriptionTh: 'แหล่งท่องเที่ยวเชิงวัฒนธรรมและตลาดน้ำเพื่อการช็อปปิ้งของนักท่องเที่ยว',
    landPrice: 2200000,
  },
  {
    id: 33,
    name: 'Tiffany Show',
    nameTh: 'ทิฟฟานี่โชว์',
    zone: 'Pattaya',
    zoneTh: 'พัทยา',
    category: 'show',
    description: 'Famous stage show and entertainment landmark in Pattaya.',
    descriptionTh: 'คาบาเรต์โชว์ระดับตำนานและแลนด์มาร์กความบันเทิงระดับโลกในพัทยา',
    landPrice: 2600000,
  },
  {
    id: 34,
    name: 'Jomtien Beach',
    nameTh: 'หาดจอมเทียน',
    zone: 'Pattaya',
    zoneTh: 'พัทยา',
    category: 'beach',
    description: 'Major beach zone for tourism, restaurants, and long-stay visitors.',
    descriptionTh: 'ชายหาดหลักสำหรับท่องเที่ยว ร้านอาหารริมทะเล และนักท่องเที่ยวพำนักระยะยาว',
    landPrice: 2800000,
  },
  {
    id: 35,
    name: 'Sanctuary of Truth',
    nameTh: 'ปราสาทสัจธรรม',
    zone: 'Pattaya',
    zoneTh: 'พัทยา',
    category: 'landmark',
    description: 'Iconic cultural landmark with high tourism draw.',
    descriptionTh: 'สถาปัตยกรรมไม้แกะสลักอันงดงามและแลนด์มาร์กวัฒนธรรมยอดนิยม',
    landPrice: 3000000,
  },
  {
    id: 36,
    name: 'Nong Nooch Garden',
    nameTh: 'สวนนงนุช',
    zone: 'Pattaya',
    zoneTh: 'พัทยา',
    category: 'themepark',
    description: 'Large garden and attraction complex with strong visitor volume.',
    descriptionTh: 'สวนพฤกษศาสตร์และศูนย์แสดงวัฒนธรรมขนาดใหญ่ที่มีปริมาณนักท่องเที่ยวเข้าชมสูงมาก',
    landPrice: 3200000,
  },
  {
    id: 37,
    name: 'Columbia Pictures Aquaverse',
    nameTh: 'โคลัมเบีย พิคเจอร์ส อควาเวิร์ส',
    zone: 'Pattaya',
    zoneTh: 'พัทยา',
    category: 'themepark',
    description: 'Movie-themed water park attraction near Pattaya.',
    descriptionTh: 'สวนสนุกและสวนน้ำในธีมภาพยนตร์ฮอลลีวูดแห่งแรกของโลกใกล้พัทยา',
    landPrice: 3400000,
  },
  {
    id: 38,
    name: 'Koh Larn',
    nameTh: 'เกาะล้าน',
    zone: 'Pattaya',
    zoneTh: 'พัทยา',
    category: 'island',
    description: 'Island tourism destination connected to Pattaya travel routes.',
    descriptionTh: 'เกาะท่องเที่ยวชายทะเลสีครามที่มีชื่อเสียงของเมืองพัทยา',
    landPrice: 3600000,
  },
  {
    id: 39,
    name: 'Walking Street Pattaya',
    nameTh: 'วอล์กกิ้งสตรีท พัทยา',
    zone: 'Pattaya',
    zoneTh: 'พัทยา',
    category: 'nightlife',
    description: 'High-traffic nightlife district with premium commercial value.',
    descriptionTh: 'แหล่งท่องเที่ยวราตรีที่คึกคักที่สุดและมีมูลค่าทางพาณิชย์สูงมากระดับพรีเมียม',
    landPrice: 4000000,
  },
]
